import { RegionCode, MealItem } from '../types/nutrition';

export const REGIONAL_METADATA: Record<RegionCode, { name: string; icon: string; subtitle: string; staples: string[] }> = {
  north_america_western: {
    name: 'North American & Western',
    icon: '🥑',
    subtitle: 'Lean proteins, oats, sweet potatoes & fresh greens',
    staples: ['Oats', 'Chicken Breast', 'Salmon', 'Sweet Potatoes', 'Greek Yogurt', 'Quinoa'],
  },
  mediterranean: {
    name: 'Mediterranean & Middle Eastern',
    icon: '🫒',
    subtitle: 'Heart-healthy olive oil, legumes, grilled seafood & whole grains',
    staples: ['Extra Virgin Olive Oil', 'Lentils', 'Chickpeas', 'Sea Bass', 'Feta', 'Bulgur'],
  },
  west_african: {
    name: 'West African & Caribbean',
    icon: '🥘',
    subtitle: 'Flavorful spiced stews, plantains, grains & grilled lean fish',
    staples: ['Jollof Brown Rice', 'Moin Moin', 'Plantains', 'Grilled Tilapia', 'Egusi', 'Okra'],
  },
  east_asian: {
    name: 'East & Southeast Asian',
    icon: '🥢',
    subtitle: 'High-protein tofu, fresh aromatics, steamed seafood & fermented veggies',
    staples: ['Brown Jasmine Rice', 'Firm Tofu', 'Edamame', 'Steamed Salmon', 'Bok Choy', 'Kimchi'],
  },
  south_asian: {
    name: 'South Asian',
    icon: '🍛',
    subtitle: 'Protein-packed dals, spiced paneer/chicken, rotis & fiber-rich veggies',
    staples: ['Yellow Lentils (Dal)', 'Paneer Tikka', 'Tandoori Chicken', 'Whole Wheat Roti', 'Chana Masala'],
  },
};

export const MEAL_DATABASE: MealItem[] = [
  // 1. NORTH AMERICA / WESTERN
  {
    id: 'w_b_1',
    title: 'Berry Protein Power Oats',
    slot: 'breakfast',
    region: 'north_america_western',
    calories: 420,
    proteinGrams: 32,
    carbsGrams: 52,
    fatGrams: 10,
    prepTimeMinutes: 10,
    dietaryTags: ['vegetarian', 'omnivore'],
    description: 'Steel-cut rolled oats cooked in almond milk, folded with vanilla whey/plant protein, chia seeds, and fresh wild blueberries.',
    ingredients: [
      { name: 'Rolled Oats', amount: '60g' },
      { name: 'Vanilla Protein Powder', amount: '30g' },
      { name: 'Fresh Blueberries', amount: '75g' },
      { name: 'Chia Seeds', amount: '10g' },
      { name: 'Almond Milk (Unsweetened)', amount: '200ml' },
    ],
    instructions: ['Simmer oats in almond milk for 5 mins.', 'Stir in protein powder and chia seeds.', 'Top with fresh blueberries and a dash of cinnamon.'],
  },
  {
    id: 'w_l_1',
    title: 'Grilled Herb Chicken & Quinoa Bowl',
    slot: 'lunch',
    region: 'north_america_western',
    calories: 540,
    proteinGrams: 46,
    carbsGrams: 55,
    fatGrams: 14,
    prepTimeMinutes: 20,
    dietaryTags: ['omnivore', 'halal'],
    description: 'Juicy rosemary-marinated chicken breast served over fluffy tri-color quinoa, roasted zucchini, and avocado slices.',
    ingredients: [
      { name: 'Chicken Breast', amount: '180g' },
      { name: 'Cooked Tri-Color Quinoa', amount: '150g' },
      { name: 'Roasted Zucchini & Bell Pepper', amount: '120g' },
      { name: 'Avocado', amount: '40g' },
      { name: 'Olive Oil & Lemon Dressing', amount: '10ml' },
    ],
    instructions: ['Grill chicken seasoned with rosemary, garlic, and sea salt.', 'Toss warm quinoa with roasted vegetables.', 'Slice chicken, top bowl with avocado and lemon dressing.'],
  },
  {
    id: 'w_d_1',
    title: 'Pan-Seared Salmon with Sweet Potato Mash',
    slot: 'dinner',
    region: 'north_america_western',
    calories: 580,
    proteinGrams: 42,
    carbsGrams: 48,
    fatGrams: 22,
    prepTimeMinutes: 25,
    dietaryTags: ['pescatarian', 'omnivore'],
    description: 'Crispy skin wild salmon rich in Omega-3s paired with roasted sweet potato mash and steamed garlic asparagus.',
    ingredients: [
      { name: 'Wild Atlantic Salmon Fillet', amount: '170g' },
      { name: 'Roasted Sweet Potato', amount: '180g' },
      { name: 'Asparagus Spears', amount: '100g' },
      { name: 'Olive Oil', amount: '8ml' },
    ],
    instructions: ['Sear salmon in a hot skillet for 4 mins per side.', 'Mash baked sweet potato with a pinch of sea salt.', 'Steam asparagus and serve alongside salmon with lemon wedge.'],
  },
  {
    id: 'w_s_1',
    title: 'Greek Yogurt with Crushed Walnuts & Honey',
    slot: 'snack',
    region: 'north_america_western',
    calories: 220,
    proteinGrams: 18,
    carbsGrams: 16,
    fatGrams: 9,
    prepTimeMinutes: 3,
    dietaryTags: ['vegetarian', 'omnivore'],
    description: 'Creamy 0% Greek yogurt layered with raw walnuts and a light drizzle of raw honey.',
    ingredients: [
      { name: '0% Fat Greek Yogurt', amount: '170g' },
      { name: 'Raw Walnuts', amount: '15g' },
      { name: 'Pure Honey', amount: '8g' },
    ],
    instructions: ['Scoop yogurt into a bowl.', 'Top with crushed walnuts and drizzle honey.'],
  },

  // 2. MEDITERRANEAN & MIDDLE EASTERN
  {
    id: 'm_b_1',
    title: 'Mediterranean Shakshuka with Feta',
    slot: 'breakfast',
    region: 'mediterranean',
    calories: 390,
    proteinGrams: 24,
    carbsGrams: 28,
    fatGrams: 20,
    prepTimeMinutes: 15,
    dietaryTags: ['vegetarian', 'omnivore', 'halal', 'kosher'],
    description: 'Poached free-range eggs simmered in a spiced tomato, red pepper, and cumin sauce, topped with crumbled feta cheese.',
    ingredients: [
      { name: 'Free-Range Eggs', amount: '2 large' },
      { name: 'Crushed Tomato Sauce with Bell Pepper', amount: '150g' },
      { name: 'Crumbled Greek Feta', amount: '30g' },
      { name: 'Whole Wheat Pita', amount: '1 piece' },
      { name: 'Extra Virgin Olive Oil', amount: '8ml' },
    ],
    instructions: ['Simmer tomatoes, peppers, cumin, and garlic in a skillet.', 'Create wells and crack in the eggs.', 'Cover until whites set, crumble feta over top, and serve with pita.'],
  },
  {
    id: 'm_l_1',
    title: 'Lemon Herb Sea Bass & Bulgur Pilaf',
    slot: 'lunch',
    region: 'mediterranean',
    calories: 520,
    proteinGrams: 44,
    carbsGrams: 50,
    fatGrams: 15,
    prepTimeMinutes: 22,
    dietaryTags: ['pescatarian', 'omnivore', 'halal'],
    description: 'Tender Mediterranean sea bass fillet seasoned with oregano, parsley, and lemon over fragrant bulgur wheat and kalamata olives.',
    ingredients: [
      { name: 'Sea Bass Fillet', amount: '180g' },
      { name: 'Cooked Bulgur Wheat', amount: '150g' },
      { name: 'Cherry Tomatoes & Cucumbers', amount: '100g' },
      { name: 'Kalamata Olives', amount: '20g' },
      { name: 'Extra Virgin Olive Oil', amount: '10ml' },
    ],
    instructions: ['Bake sea bass at 200°C for 12 mins with lemon and oregano.', 'Toss bulgur with diced tomatoes, cucumbers, and olives.', 'Serve hot with olive oil drizzle.'],
  },
  {
    id: 'm_d_1',
    title: 'Moroccan Spiced Lentil & Chickpea Tagine',
    slot: 'dinner',
    region: 'mediterranean',
    calories: 510,
    proteinGrams: 28,
    carbsGrams: 68,
    fatGrams: 12,
    prepTimeMinutes: 25,
    dietaryTags: ['vegan', 'vegetarian', 'halal', 'kosher'],
    description: 'Slow-simmered brown lentils and chickpeas in a fragrant turmeric, cinnamon, and ginger broth with butternut squash.',
    ingredients: [
      { name: 'Cooked Brown Lentils', amount: '130g' },
      { name: 'Cooked Chickpeas', amount: '120g' },
      { name: 'Roasted Butternut Squash', amount: '100g' },
      { name: 'Spinach', amount: '60g' },
      { name: 'Whole Wheat Couscous', amount: '100g' },
    ],
    instructions: ['Simmer lentils, chickpeas, and squash in Moroccan spiced tomato broth.', 'Fold in fresh spinach until wilted.', 'Serve over warm whole wheat couscous.'],
  },
  {
    id: 'm_s_1',
    title: 'Authentic Hummus with Cucumber Sticks',
    slot: 'snack',
    region: 'mediterranean',
    calories: 190,
    proteinGrams: 9,
    carbsGrams: 18,
    fatGrams: 10,
    prepTimeMinutes: 3,
    dietaryTags: ['vegan', 'vegetarian', 'halal', 'kosher'],
    description: 'Velvety chickpea and tahini hummus with crunchy crisp cucumber spears.',
    ingredients: [
      { name: 'Tahini Hummus', amount: '60g' },
      { name: 'English Cucumber', amount: '120g' },
      { name: 'Paprika & Olive Oil', amount: '3ml' },
    ],
    instructions: ['Scoop hummus into a ramekin.', 'Dust with smoked paprika and serve with sliced cucumbers.'],
  },

  // 3. WEST AFRICAN & CARIBBEAN
  {
    id: 'wa_b_1',
    title: 'Spiced Akara (Bean Cakes) with Pap Oats',
    slot: 'breakfast',
    region: 'west_african',
    calories: 410,
    proteinGrams: 26,
    carbsGrams: 54,
    fatGrams: 9,
    prepTimeMinutes: 18,
    dietaryTags: ['vegan', 'vegetarian', 'halal'],
    description: 'Golden air-fried black-eyed bean fritters spiced with habanero and onions, served with fortified warm grain porridge.',
    ingredients: [
      { name: 'Black-Eyed Pea Batter (Air-Fried)', amount: '140g' },
      { name: 'Oatmeal Porridge with Cinnamon', amount: '180g' },
      { name: 'Diced Onions & Habanero', amount: '20g' },
    ],
    instructions: ['Whip bean batter until fluffy and air-fry until golden.', 'Cook oats with water or almond milk.', 'Serve warm akara alongside porridge.'],
  },
  {
    id: 'wa_l_1',
    title: 'Jollof Brown Rice with Grilled Tilapia & Plantain',
    slot: 'lunch',
    region: 'west_african',
    calories: 560,
    proteinGrams: 45,
    carbsGrams: 64,
    fatGrams: 14,
    prepTimeMinutes: 30,
    dietaryTags: ['pescatarian', 'omnivore', 'halal'],
    description: 'Smoky party-style jollof made with fiber-rich brown rice, served with grilled herb tilapia fillet and air-fried sweet plantains.',
    ingredients: [
      { name: 'Grilled Tilapia Fillet', amount: '180g' },
      { name: 'Jollof Brown Rice', amount: '160g' },
      { name: 'Air-Fried Sweet Plantains', amount: '60g' },
      { name: 'Steamed Spinach / Efo', amount: '80g' },
    ],
    instructions: ['Season tilapia with ginger, garlic, and suya spice; grill to perfection.', 'Serve with smoky brown jollof rice, air-fried plantain slices, and steamed greens.'],
  },
  {
    id: 'wa_d_1',
    title: 'Lean Stewed Chicken with Steamed Moin Moin',
    slot: 'dinner',
    region: 'west_african',
    calories: 530,
    proteinGrams: 50,
    carbsGrams: 42,
    fatGrams: 16,
    prepTimeMinutes: 25,
    dietaryTags: ['omnivore', 'halal'],
    description: 'Tender chicken breast in rich roasted red bell pepper and tomato stew, served with steamed protein-rich bean pudding.',
    ingredients: [
      { name: 'Skinless Chicken Breast in Tomato Stew', amount: '180g' },
      { name: 'Steamed Moin Moin (Bean Cake)', amount: '140g' },
      { name: 'Steamed Broccoli or Okra', amount: '100g' },
    ],
    instructions: ['Simmer seared chicken in roasted red pepper and tomato base.', 'Unwrap freshly steamed moin moin.', 'Plate stewed chicken with moin moin and steamed okra.'],
  },
  {
    id: 'wa_s_1',
    title: 'Roasted Spiced Plantain Chips & Peanuts',
    slot: 'snack',
    region: 'west_african',
    calories: 210,
    proteinGrams: 8,
    carbsGrams: 24,
    fatGrams: 10,
    prepTimeMinutes: 2,
    dietaryTags: ['vegan', 'vegetarian', 'halal'],
    description: 'Baked unripe crunchy plantain slices paired with roasted Nigerian peanuts.',
    ingredients: [
      { name: 'Baked Plantain Slices', amount: '35g' },
      { name: 'Roasted Peanuts', amount: '20g' },
    ],
    instructions: ['Combine baked chips and peanuts for a satisfying high-protein crunch.'],
  },

  // 4. EAST & SOUTHEAST ASIAN
  {
    id: 'ea_b_1',
    title: 'Tofu & Egg Scramble with Miso Soup',
    slot: 'breakfast',
    region: 'east_asian',
    calories: 380,
    proteinGrams: 28,
    carbsGrams: 26,
    fatGrams: 17,
    prepTimeMinutes: 12,
    dietaryTags: ['vegetarian', 'pescatarian', 'omnivore', 'halal'],
    description: 'Silken tofu and egg scramble with scallions and sesame oil, served alongside probiotic-rich seaweed miso soup.',
    ingredients: [
      { name: 'Firm Tofu', amount: '120g' },
      { name: 'Egg', amount: '1 large' },
      { name: 'Miso Broth with Wakame', amount: '220ml' },
      { name: 'Brown Rice Cake / Toast', amount: '1 piece' },
      { name: 'Sesame Oil & Scallions', amount: '5ml' },
    ],
    instructions: ['Scramble crumbled tofu and egg with scallions and sesame oil.', 'Dissolve miso paste in simmering dashi broth with seaweed.', 'Serve scramble hot with bowl of miso soup.'],
  },
  {
    id: 'ea_l_1',
    title: 'Steamed Salmon with Bok Choy & Jasmine Rice',
    slot: 'lunch',
    region: 'east_asian',
    calories: 540,
    proteinGrams: 42,
    carbsGrams: 52,
    fatGrams: 18,
    prepTimeMinutes: 18,
    dietaryTags: ['pescatarian', 'omnivore', 'halal'],
    description: 'Ginger and soy-steamed salmon fillet over fragrant brown jasmine rice with garlic-tossed baby bok choy and kimchi.',
    ingredients: [
      { name: 'Fresh Salmon Fillet', amount: '170g' },
      { name: 'Brown Jasmine Rice', amount: '140g' },
      { name: 'Baby Bok Choy', amount: '120g' },
      { name: 'Fermented Kimchi', amount: '40g' },
      { name: 'Low-Sodium Soy & Ginger Glaze', amount: '15ml' },
    ],
    instructions: ['Steam salmon on a bed of ginger and scallions for 10 mins.', 'Saute bok choy with minced garlic.', 'Assemble bowl with brown rice, salmon, greens, and kimchi.'],
  },
  {
    id: 'ea_d_1',
    title: 'Chicken Teriyaki & Edamame Soba Noodles',
    slot: 'dinner',
    region: 'east_asian',
    calories: 560,
    proteinGrams: 48,
    carbsGrams: 58,
    fatGrams: 14,
    prepTimeMinutes: 20,
    dietaryTags: ['omnivore', 'halal'],
    description: 'Grilled skinless chicken strips tossed in homemade low-sugar teriyaki glaze with 100% buckwheat soba and shelled edamame.',
    ingredients: [
      { name: 'Chicken Breast Strips', amount: '180g' },
      { name: 'Buckwheat Soba Noodles', amount: '130g' },
      { name: 'Shelled Edamame', amount: '60g' },
      { name: 'Shredded Carrots & Snap Peas', amount: '80g' },
    ],
    instructions: ['Boil buckwheat soba for 5 mins and rinse under cold water.', 'Stir-fry chicken strips with snap peas and carrots.', 'Toss noodles, edamame, and chicken in light teriyaki sauce.'],
  },
  {
    id: 'ea_s_1',
    title: 'Sea Salt Steamed Edamame Pods',
    slot: 'snack',
    region: 'east_asian',
    calories: 180,
    proteinGrams: 16,
    carbsGrams: 13,
    fatGrams: 7,
    prepTimeMinutes: 5,
    dietaryTags: ['vegan', 'vegetarian', 'halal', 'kosher'],
    description: 'Warm steamed young soybeans in pods dusted with coarse flaky sea salt and toasted sesame seeds.',
    ingredients: [
      { name: 'Edamame Pods', amount: '150g' },
      { name: 'Coarse Sea Salt & Sesame', amount: '3g' },
    ],
    instructions: ['Steam edamame pods for 4 mins.', 'Toss with sea salt and toasted sesame seeds.'],
  },

  // 5. SOUTH ASIAN
  {
    id: 'sa_b_1',
    title: 'Moong Dal Chilla (Savory Crepes) with Mint Chutney',
    slot: 'breakfast',
    region: 'south_asian',
    calories: 390,
    proteinGrams: 25,
    carbsGrams: 48,
    fatGrams: 10,
    prepTimeMinutes: 15,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'kosher'],
    description: 'Crispy yellow lentil savory pancakes packed with ginger, green chili, and grated paneer/tofu, served with fresh mint chutney.',
    ingredients: [
      { name: 'Yellow Moong Dal Batter', amount: '140g' },
      { name: 'Grated Low-Fat Paneer / Tofu', amount: '40g' },
      { name: 'Fresh Mint & Coriander Chutney', amount: '30g' },
      { name: 'Ghee or Mustard Oil', amount: '5ml' },
    ],
    instructions: ['Pour dal batter onto a hot tawa and spread thin.', 'Sprinkle grated paneer and fold into a crepe.', 'Serve crisp with cooling mint chutney.'],
  },
  {
    id: 'sa_l_1',
    title: 'Tandoori Chicken Breast with Palak (Spinach) & Roti',
    slot: 'lunch',
    region: 'south_asian',
    calories: 550,
    proteinGrams: 52,
    carbsGrams: 48,
    fatGrams: 15,
    prepTimeMinutes: 25,
    dietaryTags: ['omnivore', 'halal'],
    description: 'Smoky spiced tandoori grilled chicken breast served with aromatic garlic spinach puree and whole wheat phulka roti.',
    ingredients: [
      { name: 'Tandoori Chicken Breast', amount: '190g' },
      { name: 'Palak (Spiced Spinach Puree)', amount: '140g' },
      { name: 'Whole Wheat Roti', amount: '2 pieces' },
      { name: 'Cucumber Raita', amount: '50g' },
    ],
    instructions: ['Marinate chicken in yogurt and tandoori masala; grill until charred.', 'Simmer blanched spinach with garlic, cumin, and ginger.', 'Serve hot with warm rotis and raita.'],
  },
  {
    id: 'sa_d_1',
    title: 'High-Protein Tadka Dal with Turmeric Brown Rice',
    slot: 'dinner',
    region: 'south_asian',
    calories: 520,
    proteinGrams: 30,
    carbsGrams: 72,
    fatGrams: 12,
    prepTimeMinutes: 25,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'kosher'],
    description: 'Hearty mix of yellow toor and red masoor lentils tempered with cumin seeds, garlic, and tomatoes, over fragrant brown basmati.',
    ingredients: [
      { name: 'Mixed Toor & Masoor Dal', amount: '180g' },
      { name: 'Cooked Turmeric Brown Basmati Rice', amount: '160g' },
      { name: 'Tomato & Garlic Tadka', amount: '40g' },
      { name: 'Kachumber Salad (Cucumber & Tomato)', amount: '80g' },
    ],
    instructions: ['Pressure cook lentils until creamy.', 'Temper cumin, garlic, and chili in ghee; pour over dal.', 'Serve with warm brown basmati and crunchy kachumber salad.'],
  },
  {
    id: 'sa_s_1',
    title: 'Roasted Spiced Chickpeas (Chana Crunch)',
    slot: 'snack',
    region: 'south_asian',
    calories: 200,
    proteinGrams: 11,
    carbsGrams: 28,
    fatGrams: 5,
    prepTimeMinutes: 3,
    dietaryTags: ['vegan', 'vegetarian', 'halal', 'kosher'],
    description: 'Oven-roasted crunchy chickpeas tossed in chaat masala, cumin, and lemon juice.',
    ingredients: [
      { name: 'Roasted Spiced Chickpeas', amount: '60g' },
      { name: 'Chaat Masala & Lime Juice', amount: '3g' },
    ],
    instructions: ['Toss roasted chickpeas with chaat masala and a squeeze of fresh lime.'],
  },
];

export function getMealsByRegion(region: RegionCode): MealItem[] {
  return MEAL_DATABASE.filter((m) => m.region === region);
}

export function getMealById(id: string): MealItem | undefined {
  return MEAL_DATABASE.find((m) => m.id === id);
}

export function getSwapCandidates(currentMeal: MealItem): MealItem[] {
  return MEAL_DATABASE.filter((m) => m.slot === currentMeal.slot && m.id !== currentMeal.id);
}
