import { WorkoutRoutine } from '../types/workout';

export const WORKOUT_ROUTINES: WorkoutRoutine[] = [
  {
    id: 'w_bodyweight_hiit_1',
    title: 'Full Body HIIT Burner',
    difficulty: 'beginner',
    durationMinutes: 20,
    estimatedCaloriesBurned: 220,
    equipment: ['bodyweight'],
    category: 'hiit',
    description: 'A high-energy, zero-equipment fat-burning circuit designed to elevate heart rate and build functional endurance.',
    exercises: [
      {
        id: 'ex_1',
        name: 'Bodyweight Squats',
        targetMuscle: 'Quadriceps & Glutes',
        sets: 3,
        repsOrDuration: '15 reps',
        restSeconds: 30,
        instructions: 'Stand with feet shoulder-width apart. Lower hips down and back as if sitting in a chair, keeping chest upright. Drive through heels to return to standing.',
      },
      {
        id: 'ex_2',
        name: 'Incline or Floor Push-Ups',
        targetMuscle: 'Chest, Shoulders & Triceps',
        sets: 3,
        repsOrDuration: '10-12 reps',
        restSeconds: 30,
        instructions: 'Place hands slightly wider than shoulder-width. Lower chest to floor with elbows at a 45-degree angle. Push firmly back to starting plank position.',
      },
      {
        id: 'ex_3',
        name: 'Reverse Lunges',
        targetMuscle: 'Hamstrings & Glutes',
        sets: 3,
        repsOrDuration: '12 reps / leg',
        restSeconds: 30,
        instructions: 'Step backward with one leg and lower back knee toward the floor until both knees reach 90 degrees. Push back up through front heel.',
      },
      {
        id: 'ex_4',
        name: 'Mountain Climbers',
        targetMuscle: 'Core & Cardiovascular',
        sets: 3,
        repsOrDuration: '30 seconds',
        restSeconds: 45,
        instructions: 'Hold a firm high plank. Rapidly alternate driving knees toward chest while keeping hips level and core braced.',
      },
      {
        id: 'ex_5',
        name: 'Forearm Plank Hold',
        targetMuscle: 'Transverse Abdominis',
        sets: 3,
        repsOrDuration: '40 seconds',
        restSeconds: 60,
        instructions: 'Rest on forearms and toes. Keep spine neutral from head to heels, squeezing glutes and engaging core.',
      },
    ],
  },
  {
    id: 'w_dumbbell_upper_1',
    title: 'Upper Body Sculpt & Strength',
    difficulty: 'intermediate',
    durationMinutes: 30,
    estimatedCaloriesBurned: 260,
    equipment: ['dumbbells'],
    category: 'strength',
    description: 'Targeted upper body routine building sculpted shoulders, back, chest, and arms with dumbbells.',
    exercises: [
      {
        id: 'ex_db_1',
        name: 'Dumbbell Overhead Press',
        targetMuscle: 'Deltoids & Triceps',
        sets: 4,
        repsOrDuration: '10-12 reps',
        restSeconds: 45,
        instructions: 'Hold dumbbells at shoulder height with palms forward. Press overhead until arms are extended without locking elbows. Lower smoothly.',
      },
      {
        id: 'ex_db_2',
        name: 'Bent-Over Dumbbell Rows',
        targetMuscle: 'Lats & Rhomboids',
        sets: 4,
        repsOrDuration: '12 reps',
        restSeconds: 45,
        instructions: 'Hinge forward at hips with flat back. Pull dumbbells up toward hips, squeezing shoulder blades together at the top.',
      },
      {
        id: 'ex_db_3',
        name: 'Dumbbell Floor Press',
        targetMuscle: 'Pectorals & Triceps',
        sets: 3,
        repsOrDuration: '12 reps',
        restSeconds: 45,
        instructions: 'Lie flat on floor with knees bent. Press dumbbells up from chest level until arms are straight.',
      },
      {
        id: 'ex_db_4',
        name: 'Bicep Curl to Hammer Press',
        targetMuscle: 'Biceps & Forearms',
        sets: 3,
        repsOrDuration: '12 reps',
        restSeconds: 30,
        instructions: 'Curl weights with palms up, rotate palms facing inward at top, and lower with control.',
      },
      {
        id: 'ex_db_5',
        name: 'Overhead Tricep Extension',
        targetMuscle: 'Triceps',
        sets: 3,
        repsOrDuration: '12 reps',
        restSeconds: 45,
        instructions: 'Hold a single dumbbell overhead with both hands. Lower behind head bending at elbows, then press back up.',
      },
    ],
  },
  {
    id: 'w_lower_strength_1',
    title: 'Glute & Leg Power Circuit',
    difficulty: 'intermediate',
    durationMinutes: 28,
    estimatedCaloriesBurned: 270,
    equipment: ['bodyweight', 'dumbbells'],
    category: 'strength',
    description: 'Build lower body stability, explosive power, and lean muscle with targeted compound movements.',
    exercises: [
      {
        id: 'ex_leg_1',
        name: 'Goblet Squats',
        targetMuscle: 'Quadriceps & Core',
        sets: 4,
        repsOrDuration: '12 reps',
        restSeconds: 45,
        instructions: 'Hold dumbbell vertically at chest level. Squat deep keeping elbows inside knees, drive up through midfoot.',
      },
      {
        id: 'ex_leg_2',
        name: 'Romanian Deadlifts',
        targetMuscle: 'Hamstrings & Glute-Ham Tie-In',
        sets: 4,
        repsOrDuration: '10-12 reps',
        restSeconds: 45,
        instructions: 'Hinge hips backward with soft knees and straight back. Lower weights along shins until hamstrings stretch, then snap hips forward.',
      },
      {
        id: 'ex_leg_3',
        name: 'Bulgarian Split Squats',
        targetMuscle: 'Unilateral Quads & Glutes',
        sets: 3,
        repsOrDuration: '10 reps / leg',
        restSeconds: 45,
        instructions: 'Place rear foot elevated on a chair/bench. Lower front knee until thigh is parallel to ground. Drive up through front heel.',
      },
      {
        id: 'ex_leg_4',
        name: 'Glute Bridge Holds',
        targetMuscle: 'Gluteus Maximus',
        sets: 3,
        repsOrDuration: '15 reps (2s hold)',
        restSeconds: 30,
        instructions: 'Lie on back with knees bent. Drive hips to ceiling, squeezing glutes hard at the apex for 2 full seconds.',
      },
    ],
  },
  {
    id: 'w_core_mobility_1',
    title: 'Core Stability & Mobility Flow',
    difficulty: 'beginner',
    durationMinutes: 15,
    estimatedCaloriesBurned: 120,
    equipment: ['bodyweight'],
    category: 'core',
    description: 'Decompress spine, strengthen transverse abs, and improve hip mobility for posture and injury prevention.',
    exercises: [
      {
        id: 'ex_cor_1',
        name: 'Deadbugs',
        targetMuscle: 'Deep Core Stabilizers',
        sets: 3,
        repsOrDuration: '12 reps / side',
        restSeconds: 30,
        instructions: 'Lie on back with arms extended up and knees at 90 degrees. Lower opposite arm and leg toward floor without arching lower back.',
      },
      {
        id: 'ex_cor_2',
        name: 'Bird-Dog Cross Reaches',
        targetMuscle: 'Posterior Chain & Core',
        sets: 3,
        repsOrDuration: '10 reps / side',
        restSeconds: 30,
        instructions: 'On hands and knees, extend opposite arm and leg straight out. Touch elbow to knee under torso and repeat.',
      },
      {
        id: 'ex_cor_3',
        name: 'Side Plank Holds',
        targetMuscle: 'Obliques & Quadratus Lumborum',
        sets: 3,
        repsOrDuration: '30s / side',
        restSeconds: 30,
        instructions: 'Prop up on one forearm with body in a straight diagonal line. Hold hips high without sagging.',
      },
      {
        id: 'ex_cor_4',
        name: 'World\'s Greatest Stretch',
        targetMuscle: 'Hip Flexors, Thoracic Spine, Hamstrings',
        sets: 2,
        repsOrDuration: '6 reps / side',
        restSeconds: 30,
        instructions: 'Lunge forward with hands inside front foot. Rotate torso reaching front arm to ceiling, opening chest.',
      },
    ],
  },
  {
    id: 'w_band_fullbody_1',
    title: 'Total Body Band Activation',
    difficulty: 'beginner',
    durationMinutes: 22,
    estimatedCaloriesBurned: 190,
    equipment: ['resistance_bands'],
    category: 'strength',
    description: 'Joint-friendly resistance band circuit targeting upper, lower, and core musculature with continuous tension.',
    exercises: [
      {
        id: 'ex_bnd_1',
        name: 'Band-Resisted Squats',
        targetMuscle: 'Quadriceps & Glute Medius',
        sets: 3,
        repsOrDuration: '15 reps',
        restSeconds: 30,
        instructions: 'Loop loop band just above knees. Squat while keeping knees tracking outward against the resistance.',
      },
      {
        id: 'ex_bnd_2',
        name: 'Banded Face Pulls & Pull-Aparts',
        targetMuscle: 'Rear Delts & Upper Back',
        sets: 3,
        repsOrDuration: '15 reps',
        restSeconds: 30,
        instructions: 'Hold band with straight arms at shoulder height. Pull band apart by retracting shoulder blades until hands reach chest line.',
      },
      {
        id: 'ex_bnd_3',
        name: 'Standing Banded Chest Press',
        targetMuscle: 'Pectorals & Triceps',
        sets: 3,
        repsOrDuration: '12-15 reps',
        restSeconds: 30,
        instructions: 'Anchor band behind back at mid-chest height. Press handles forward until arms are extended, squeezing chest.',
      },
      {
        id: 'ex_bnd_4',
        name: 'Banded Pallof Press',
        targetMuscle: 'Anti-Rotation Core',
        sets: 3,
        repsOrDuration: '10 reps / side',
        restSeconds: 30,
        instructions: 'Anchor band at chest height. Stand perpendicular, hold handle at sternum, and press straight out resisting rotational pull.',
      },
    ],
  },
  {
    id: 'w_gym_power_1',
    title: 'Gym Compound Power Split',
    difficulty: 'intermediate',
    durationMinutes: 35,
    estimatedCaloriesBurned: 320,
    equipment: ['full_gym'],
    category: 'strength',
    description: 'Foundational compound gym movements maximizing progressive overload and functional hypertrophy.',
    exercises: [
      {
        id: 'ex_gym_1',
        name: 'Barbell or Machine Chest Press',
        targetMuscle: 'Chest, Anterior Delts',
        sets: 4,
        repsOrDuration: '8-10 reps',
        restSeconds: 60,
        instructions: 'Plant feet flat. Lower bar smoothly to mid-chest and drive up aggressively without locking elbows.',
      },
      {
        id: 'ex_gym_2',
        name: 'Lat Pulldowns or Cable Rows',
        targetMuscle: 'Latissimus Dorsi',
        sets: 4,
        repsOrDuration: '10-12 reps',
        restSeconds: 60,
        instructions: 'Grip bar slightly wider than shoulders. Pull down to upper collarbone driving elbows down and back.',
      },
      {
        id: 'ex_gym_3',
        name: 'Leg Press or Hack Squats',
        targetMuscle: 'Quads & Glutes',
        sets: 4,
        repsOrDuration: '10-12 reps',
        restSeconds: 60,
        instructions: 'Place feet shoulder-width on platform. Lower sled under control until knees reach 90 degrees, press through whole foot.',
      },
      {
        id: 'ex_gym_4',
        name: 'Hanging Leg or Knee Raises',
        targetMuscle: 'Lower Rectus Abdominis',
        sets: 3,
        repsOrDuration: '12 reps',
        restSeconds: 45,
        instructions: 'Hang from pull-up bar. Curl knees toward chest avoiding swinging, lower with controlled tempo.',
      },
    ],
  },
];

export function getWorkoutById(id: string): WorkoutRoutine | undefined {
  return WORKOUT_ROUTINES.find((w) => w.id === id);
}

export function getWorkoutsByEquipment(userEquipment: string[]): WorkoutRoutine[] {
  return WORKOUT_ROUTINES.filter((routine) =>
    routine.equipment.some((eq) => userEquipment.includes(eq) || eq === 'bodyweight')
  );
}
